export const template = [
  {
    element: "LONG_READ_BLOCK",
    title: "",
    subElements: [
      {
        element: "TEXT_BLOCK",
        text: "Информируем о том, что туроператорскую деятельность вправе осуществлять только зарегистрированные на территории Российской Федерации юридические лица, имеющие финансовое обеспечение, и сведения о которых внесены в Единый федеральный реестр туроператоров (в соответствии со статьей 41 Федерального закона от 24 ноября 1996 г. № 132-ФЗ «Об основах туристской деятельности в Российской Федерации). Осуществление туроператорской деятельности с нарушением данного законодательства не допускается. Перечень туроператоров Рязанской области, сведения о которых внесены в Единый федеральный реестр туроператоров \n\n <table><tbody><tr><td>№</td><td>Наименование</td><td><p>Контактная информация</p></td><td>Реестровый номер</td></tr><tr><td>1</td><td>ООО «МК-тревел»</td><td><p>Рязань, Краснорядская, 21</p><p>+7(4912) 20 62 03</p><p>info@mk-travel.ru</p><p><a href='https://mk-travel.ru/' target='_blank' rel='noopener'>mk-travel.ru</a></p></td><td>РТО 002957</td></tr><tr><td>2</td><td>ООО «Добродей»</td><td><p>Рязань, Первомайский просп., 33А, офис 3&nbsp;</p><p>+7 (4912) 90 13 82</p><p>&nbsp;tour@dobrodey.ru, &nbsp;dobrodeyrzn@yandex.ru</p><p><a href='https://www.dobrodey.ru/' target='_blank' rel='noopener'>www.dobrodey.ru</a></p></td><td>РТО 003266</td></tr><tr><td>3</td><td>ООО «САФАРИ-ТУР»</td><td><p>Рязань, Ленина, 49, пом. Н4, офис 22</p><p>+7 (4912) 51 56 15</p><p><a href='https://xn--80aay5abblie.xn--p1ai/' target='_blank' rel='noopener'>сафаритур.рф</a></p></td><td>РТО 024996</td></tr><tr><td>4</td><td>ООО Туристическое агентство «Орбита»</td><td><p>Рязань, Первомайский просп., 7, офис 16</p><p>+7 (4912) 90 41 59</p><p>orbitatur@yandex.ru</p><p><a href='https://orbitarzn.ru/' target='_blank' rel='noopener'>orbitarzn.ru</a></p></td><td>РТО 000059</td></tr><tr><td>5</td><td>ООО «ЦЕНТР-ТУР»</td><td><p>Рязань, Право-Лыбедская, 40, лит. А, пом. Н30, офис 21</p><p>+7 (4912) 95 85 50</p><p>c-tur@nxt.ru</p><p><a href='https://www.c-tur.ru/' target='_blank' rel='noopener'>www.c-tur.ru</a></p></td><td>РТО 011683</td></tr><tr><td>6</td><td>ООО «Центральное туристическое агентство»</td><td><p>Рязань, Соборная, 17, кв. 9</p><p>&nbsp;+7 (4912) 27 28 28</p><p><a href='https://www.cta62.ru/' target='_blank' rel='noopener'>www.cta62.ru</a></p></td><td>РТО 006840</td></tr><tr><td>7</td><td>ООО «АРГО ТУР»</td><td><p>Рязань, Семена Середы, 29/1, офис 21</p><p>+7(4912) 22 82 20</p><p><a href='https://www.argo-tours.ru' target='_blank' rel='noopener'>www.argo-tours.ru</a></p></td><td>РТО 025436</td></tr></tbody></table>",
      },
    ],
  },
];
